### ISSUE TITLE
What is difference between variable_batch_sampler and multi_scale_sampler?

### ISSUE THREAD

**Issue by YHYeooooong** [apple/ml-cvnets#32] opened 2022-07-04 05:24 UTC
Hello, Thanks for sharing your great work!

I want to train the Mobilevit model with a multi-scale sampler, but I can not find any .yaml file for it. (In classification task)
The Mobilevit .yaml file in config/classification/imagenet uses a variable batch sampler, also Mobilevit V2 uses the same thing in training.

Is the variable batch sampler the same as the multi-scale sampler?   
What should I use? Multi-scale sampler or variable batch sampler?

**Comment by farzadab** [comment] 2022-07-04 07:18
Hi!

No, they are not the same. You can read about them in our documentation:
https://apple.github.io/ml-cvnets/data_samplers.html
The CVNets paper also covers the differences of MSc-FBS and MSc-VBS in
section 3.1: https://arxiv.org/abs/2206.02002

The short answer is: you probably want to use MSc-VBS because it gives you
the speed-up without the extra GPU Memory cost.

[image: image.png]

Also note that variable batch sample, aka MSc-VBS, is a multi-scale sampler
too.

Hope that helps.

**Comment by sacmehta** [comment] 2022-07-14 04:25
It appears that the issue is resolved. So, closing it. Feel free to re-open in case you need more information about variable batch sampler and multi-scale sampler

**Closed by sacmehta** 2022-07-14 04:25 UTC
